apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse-01"
  namespace: clickhouse  # facultatif, adapte selon ton cas
spec:
  configuration:
    users:
      demo/default: secret
      demo/password: 12345678
      demo/profile: default
      demo/quota: default
      demo/networks/ip: "::/0"
    clusters:
      - name: "clickhouse-01"
        layout:
          type: "Standard"
          shardsCount: 1
          replicasCount: 1
  defaults:
    templates:
      podTemplates:
        - name: clickhouse-stable
          podTemplateSpec:
            containers:
              - name: clickhouse
                image: yandex/clickhouse-server:19.4.3.11
                # resources:
                #   requests:
                #     memory: "512Mi"
                #     cpu: "500m"
                #   limits:
                #     memory: "512Mi"
                #     cpu: "500m"
      volumeClaimTemplates:
        - name: storage-vc-template
          spec:
            storageClassName: longhorn
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
      serviceTemplates:
        - name: clickhouse-service
          generateName: "clickhouse-service"
          spec:
            type: NodePort
            ports:
              - name: http
                port: 8123
                targetPort: 8123
                nodePort: 30123
              - name: tcp
                port: 9000
                targetPort: 9000
                nodePort: 30900
  