apiVersion: apps/v1
kind: Deployment
metadata:
  name: solfa-front  # Nom du déploiement
  namespace: solfa-space  # Espace de noms
  labels:
    app: solfa-front  # Étiquette pour l'application
spec:
  replicas: 1  # Nombre de réplicas souhaités
  selector:
    matchLabels:
      app: solfa-front  # Étiquette pour correspondre aux pods
  template:
    metadata:
      labels:
        app: solfa-front  # Étiquette pour les pods
    spec:
      containers:
        - name: solfa-front  # Nom du conteneur
          image: zetsu225/solfa:dev-f48b333d558078e9b9eaf2a7000095ee03c5530d
          ports:
            - containerPort: 8080  # Port écouté par l'application
          envFrom:
            - configMapRef:
                name: solfa-front  # Référence au ConfigMap
          # resources:
          #   limits:
          #     cpu: "500m"  # Limites de CPU
          #     memory: "600Mi"  # Limites de mémoire
          #   # requests:
          #   #   cpu: "250m"  # Requêtes de CPU
          #   #   memory: "300Mi"  # Requêtes de mémoire


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: solfa-back
  namespace: solfa-space
data:
  ES_URL: "http://10.242.68.64:9202/"


---
apiVersion: v1
kind: Service
metadata:
  name: solfa-front #service-name
  namespace: solfa-space #namespace
spec:
  selector:
    app: solfa-front #app-name
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32040 #port to be define
  type: NodePort

  