apiVersion: apps/v1
kind: Deployment
metadata:
  name: solfa-front  # Nom du déploiement
  namespace: solfa-space  # Espace de noms
  labels:
    app: solfa-front  # Étiquette pour l'application
spec:
  replicas: 1  # Nombre de réplicas souhaités
  selector:
    matchLabels:
      app: solfa-front  # Étiquette pour correspondre aux pods
  template:
    metadata:
      labels:
        app: solfa-front  # Étiquette pour les pods
    spec:
      containers:
        - name: solfa-front  # Nom du conteneur
          image: zetsu225/solfa:dev-5ff853b595be56a9ea6cd32507f0cd01e0bbf578
          ports:
            - containerPort: 8080  # Port écouté par l'application
          envFrom:
            - configMapRef:
                name: solfa-front  # Référence au ConfigMap
          # resources:
          #   limits:
          #     cpu: "500m"  # Limites de CPU
          #     memory: "600Mi"  # Limites de mémoire
          #   # requests:
          #   #   cpu: "250m"  # Requêtes de CPU
          #   #   memory: "300Mi"  # Requêtes de mémoire


---
apiVersion: v1
kind: Service
metadata:
  name: solfa-front
  namespace: solfa-space
spec:
  selector:
    app: solfa-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080   # Modifie ce port pour correspondre à celui du conteneur
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solfa-front-ingress
  namespace: solfa-space
spec:
  rules:
  - host: srv598321.hstgr.cloud
    http:
      paths:
      - path: /solfa
        pathType: Prefix
        backend:
          service:
            name: solfa-front
            port:
              number: 80