apiVersion: apps/v1
kind: Deployment
metadata:
  name: solfa-front  # Nom du déploiement
  namespace: solfa-space  # Espace de noms
  labels:
    app: solfa-front  # Étiquette pour l'application
spec:
  replicas: 1  # Nombre de réplicas souhaités
  selector:
    matchLabels:
      app: solfa-front  # Étiquette pour correspondre aux pods
  template:
    metadata:
      labels:
        app: solfa-front  # Étiquette pour les pods
    spec:
      containers:
        - name: solfa-front  # Nom du conteneur
          image: zetsu225/solfa:dev-5ff853b595be56a9ea6cd32507f0cd01e0bbf578
          ports:
            - containerPort: 80  # Port écouté par l'application
          envFrom:
            - configMapRef:
                name: solfa-front  # Référence au ConfigMap
          # resources:
          #   limits:
          #     cpu: "500m"  # Limites de CPU
          #     memory: "600Mi"  # Limites de mémoire
          #   # requests:
          #   #   cpu: "250m"  # Requêtes de CPU
          #   #   memory: "300Mi"  # Requêtes de mémoire


---
apiVersion: v1
kind: Service
metadata:
  name: solfa-front  # Nom du service
  namespace: solfa-space  # Namespace
spec:
  selector:
    app: solfa-front  # Correspond aux pods avec l'étiquette "app: solfa-front"
  ports:
    - protocol: TCP
      port: 80  # Le port que le service expose
      targetPort: 8080  # Le port que le conteneur écoute
  type: ClusterIP  # Service interne accessible par Ingress

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solfa-front-ingress  # Nom de l'Ingress
  namespace: solfa-space  # Namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"  # Réécriture des URLs pour le service
spec:
  rules:
    - host: srv598321.hstgr.cloud  # Remplacez par votre domaine ou IP publique
      http:
        paths:
          - path: /  # Chemin vers lequel router les requêtes
            pathType: Prefix
            backend:
              service:
                name: solfa-front  # Le nom du service Kubernetes
                port:
                  number: 80  # Port exposé par le service

