apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-etl
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: zetsu225/eureka:dev-95d7b65c269820e74667d795afb60c12d56fccc8
  imagePullPolicy: 
  mainApplicationFile: local:///opt/spark/work-dir/main.py
  sparkVersion: "3.3.1"
  restartPolicy:
    type: Never
  
  driver:
    cores: 1
    memory: "512m"
    labels:
      version: 3.3.1
    serviceAccount: spark
    env:
      - name: AWS_ACCESS_KEY_ID
        value: minioadmin
      - name: AWS_SECRET_ACCESS_KEY
        value: minio@demo!
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.3.1
    env:
      - name: AWS_ACCESS_KEY_ID
        value: minioadmin
      - name: AWS_SECRET_ACCESS_KEY
        value: minio@demo!
