---
# Source: trino/templates/configmap-catalog.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: presto-trino-catalog
  namespace: trino
  labels:
    helm.sh/chart: trino-0.30.0
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: presto
    app.kubernetes.io/version: "459"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: catalogs
data:
  tpcds.properties: |
    connector.name=tpcds
    tpcds.splits-per-node=4
    
  tpch.properties: |
    connector.name=tpch
    tpch.splits-per-node=4
---
# Source: trino/templates/configmap-coordinator.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: presto-trino-coordinator
  namespace: trino
  labels:
    helm.sh/chart: trino-0.30.0
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: presto
    app.kubernetes.io/version: "459"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: coordinator
data:
  node.properties: |
    node.environment=production
    node.data-dir=/data/trino
    plugin.dir=/usr/lib/trino/plugin

  jvm.config: |
    -server
    -agentpath:/usr/lib/trino/bin/libjvmkill.so
    -Xmx8G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -XX:-OmitStackTraceInFastThrow
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
    # Allow loading dynamic agent used by JOL
    -XX:+EnableDynamicAgentLoading
  
    # https://bugs.openjdk.org/browse/JDK-8329528
    -XX:+UnlockDiagnosticVMOptions
    -XX:G1NumCollectionsKeepPinned=10000000

  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    query.max-memory=4GB
    query.max-memory-per-node=1GB
    discovery.uri=http://localhost:8080

  log.properties: |
    io.trino=INFO
---
# Source: trino/templates/configmap-coordinator.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: presto-trino-schemas-volume-coordinator
  namespace: trino
  labels:
    helm.sh/chart: trino-0.30.0
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: presto
    app.kubernetes.io/version: "459"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: coordinator
data:
---
# Source: trino/templates/configmap-worker.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: presto-trino-worker
  namespace: trino
  labels:
    helm.sh/chart: trino-0.30.0
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: presto
    app.kubernetes.io/version: "459"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: worker
data:
  node.properties: |
    node.environment=production
    node.data-dir=/data/trino
    plugin.dir=/usr/lib/trino/plugin

  jvm.config: |
    -server
    -agentpath:/usr/lib/trino/bin/libjvmkill.so
    -Xmx8G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -XX:-OmitStackTraceInFastThrow
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
    # Allow loading dynamic agent used by JOL
    -XX:+EnableDynamicAgentLoading
  
    # https://bugs.openjdk.org/browse/JDK-8329528
    -XX:+UnlockDiagnosticVMOptions
    -XX:G1NumCollectionsKeepPinned=10000000

  config.properties: |
    coordinator=false
    http-server.http.port=8080
    query.max-memory=4GB
    query.max-memory-per-node=1GB
    discovery.uri=http://presto-trino:8080

  log.properties: |
    io.trino=INFO
---
# Source: trino/templates/configmap-worker.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: presto-trino-schemas-volume-worker
  namespace: trino
  labels:
    helm.sh/chart: trino-0.30.0
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: presto
    app.kubernetes.io/version: "459"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: worker
data:
---
# Source: trino/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: presto-trino
  namespace: trino
  labels:
    helm.sh/chart: trino-0.30.0
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: presto
    app.kubernetes.io/version: "459"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 31080
  selector:
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: presto
    app.kubernetes.io/component: coordinator
---
# Source: trino/templates/deployment-coordinator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: presto-trino-coordinator
  namespace: trino
  labels:
    helm.sh/chart: trino-0.30.0
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: presto
    app.kubernetes.io/version: "459"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: coordinator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: trino
      app.kubernetes.io/instance: presto
      app.kubernetes.io/component: coordinator
  template:
    metadata:
      annotations:
        checksum/catalog-config: 8d0ea7e2dbb551032f4c238c54df71cced95815d20a5920bd383ce44dac53c70
        checksum/coordinator-config: 9f05c69bf331d8c43e80d4eacc9dc34fac44a1f6422aa36de1bc86f7afd70bea

      labels:
        helm.sh/chart: trino-0.30.0
        app.kubernetes.io/name: trino
        app.kubernetes.io/instance: presto
        app.kubernetes.io/version: "459"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: coordinator
    spec:
      serviceAccountName: default
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      volumes:
        - name: config-volume
          configMap:
            name: presto-trino-coordinator
        - name: catalog-volume
          configMap:
            name: presto-trino-catalog
        - name: schemas-volume
          configMap:
            name: presto-trino-schemas-volume-coordinator
      imagePullSecrets:
        - name: registry-credentials
      terminationGracePeriodSeconds: 30
      containers:
        - name: trino-coordinator
          image: trinodb/trino:459
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          env:
            []
          envFrom:
            []
          volumeMounts:
            - mountPath: /etc/trino
              name: config-volume
            - mountPath: /etc/trino/catalog
              name: catalog-volume
            - mountPath: /etc/trino/schemas
              name: schemas-volume
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/info
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            exec:
              command: [/usr/lib/trino/bin/health-check]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          lifecycle:
            {}
          resources:
            {}
---
# Source: trino/templates/deployment-worker.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: presto-trino-worker
  namespace: trino
  labels:
    helm.sh/chart: trino-0.30.0
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: presto
    app.kubernetes.io/version: "459"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: trino
      app.kubernetes.io/instance: presto
      app.kubernetes.io/component: worker
  template:
    metadata:
      annotations:
        checksum/catalog-config: 8d0ea7e2dbb551032f4c238c54df71cced95815d20a5920bd383ce44dac53c70
        checksum/worker-config: e9f1925cf21b1e8c10a291a4f7bb27867bbb02b7386c947739236f8673866171
      labels:
        helm.sh/chart: trino-0.30.0
        app.kubernetes.io/name: trino
        app.kubernetes.io/instance: presto
        app.kubernetes.io/version: "459"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: default
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      volumes:
        - name: config-volume
          configMap:
            name: presto-trino-worker
        - name: catalog-volume
          configMap:
            name: presto-trino-catalog
        - name: schemas-volume
          configMap:
            name: presto-trino-schemas-volume-worker
      imagePullSecrets:
        - name: registry-credentials
      terminationGracePeriodSeconds: 30
      containers:
        - name: trino-worker
          image: trinodb/trino:459
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          env:
            []
          envFrom:
            []
          volumeMounts:
            - mountPath: /etc/trino
              name: config-volume
            - mountPath: /etc/trino/catalog
              name: catalog-volume
            - mountPath: /etc/trino/schemas
              name: schemas-volume
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/info
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            exec:
              command: [/usr/lib/trino/bin/health-check]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          lifecycle:
            {}
          resources:
            {}
---
# Source: trino/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: presto-trino-test-connection
  labels:
    helm.sh/chart: trino-0.30.0
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: presto
    app.kubernetes.io/version: "459"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: test
    test: connection
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: cli
      image: trinodb/trino:459
      command: ['trino']
      args:
      - trino://presto-trino:8080
      - --user=admin
      - --debug
      - --execute=SELECT 1
      - --no-progress
  restartPolicy: Never
