apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minio
spec:
  ports:
  - name: cluster
    port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 30090  # Port NodePort fixe pour le service cluster
    
  - name: console
    port: 9001
    protocol: TCP
    targetPort: 9001
    nodePort: 30091  # Port NodePort fixe pour le service console
    
  selector:
    app: minio
  type: NodePort
