---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        env:
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minio@demo!"
        - name: MINIO_DOMAIN
          value: "minio.miniodemo.xyz"
        image: minio/minio:latest
        args:
         - server   # who are our servers in cluster (below)
        #  - http://minio-0.minio.minio.svc.cluster.local/data
        #  - http://minio-1.minio.minio.svc.cluster.local/data
        #  - http://minio-2.minio.minio.svc.cluster.local/data
        # - server   # Single node setup requires a local directory path
         - /data/minio  # Corrected: single-node, single-drive path
         - --console-address   # which port for console
         - :9001
        ports:
        - containerPort: 9000
          hostPort: 9000
        - containerPort: 9001
          hostPort: 9001          
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 5Gi