apiVersion: v1
kind: ConfigMap
metadata:
  name: my-redis-config
  namespace: redis-space
data:
  maxmemory: 512mb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: redis-space
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-container
          image: redis:alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /redis-master-data
            - name: redis-config
              mountPath: /redis-master
      volumes:
        - name: redis-config
          configMap:
            name: my-redis-config
        - name: data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis-space
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30079
